### ISSUE TITLE
Output problems for example.py and import problems for dbmol.py

### ISSUE THREAD

**Issue by qfyu** [MobleyLab/Lomap#35]
Dear Lomap,

I had some problems when I tried to run the python scripts of lomap, please see the following for detial.

(1) #LINUX VERSION
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	SUSE LINUX
Description:	SUSE Linux Enterprise Server 11 (x86_64)
Release:	11
Codename:	n/a

(2) #LOMAP INSTALLATION
conda config --add channels nividic
conda create -c nividic -n my-lomap lomap
source activate my-lomap

#all prerequisites were installed 
conda list
boost                     1.56.0                   py34_1    	  nividic
graphviz                2.38.0                   1              	  mobleylab
lomap                    0.0.0                     py34_0    	  nividic
pygraphviz            1.4rc1                   py34_0    	  nividic
rdkit                       2015.09.2             np110py34_0  nividic
matplotlib              1.5.1                     np110py34_0
networkx               1.11                      py34_0
pyqt                       4.11.4                   py34_4
…..

(3) python example.py
#basic or radial 
#db_mol = lomap.DBMolecules('test/basic/', output=True)
#db_mol = lomap.DBMolecules('test/radial/', output=True)
#outputs are as following
out.txt
out_score_with_connection.txt
mcs.png

Question One: Why didn’t the script output all results? Such as out.png, out.pickle, out.pdf, out.eps, and out.doc? 

(4) #open dbmol.py and input commands 
python 
>>> from lomap import mcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'mcs'
>>> from lomap import graphgen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'graphgen'

Question Two: What caused these problems and how to solve them?
 
Thank you and look forward to your reply.

**Comment by davidlmobley** [comment]
@nividic @shuail any insights?

I'll try and see if I can reproduce your issue.

**Comment by davidlmobley** [comment]
@qfyu - I've reproduced *a* problem with this (installing in a clean conda environment), though I'm not sure it's the same as your problem; I'm getting an issue with `libc++abi.dylib` throwing an uncaught exception; if I had to guess my particular issue looks like it's a problem with graphics libraries.

Did you get any error messages when you attempted this? And what platform are you on?

Probably we need to get #34 merged in and then go through and make sure we have a build that is compatible with the latest versions of the relevant packages. We haven't been using this very much lately and I think things may have gotten a bit outdated.

**Comment by shuail** [comment]
@qfyu @davidlmobley I tried to reproduce the errors from a clean conda env. Here are steps I performed:

conda create --no-default-packages -n test-lomap-clean python
source activate test-lomap-clean
conda config --add channels nividic
conda install lomap
conda install networkx=1.11 (here since #34 is not merged yet, just manually downgrade networkx.)

After all, I go to the Lomap folder and run "python example.py", it gives me all the results. 

Here is the list of relevant packages in the conda list

boost                     1.56.0                   py27_3    nividic
graphviz                  2.38.0                        5   
lomap                     0.0.0                    py27_0    nividic
matplotlib                1.5.0               np110py27_0  
networkx                  1.11                     py27_1  
numpy                     1.10.4                   py27_2  
pygraphviz                1.3.1                    py27_3    nividic
pyqt                      4.11.4                   py27_4  
python                    2.7.15               h1571d57_0  
qt                        4.8.7                         4  
rdkit                     2016.03.1           np110py27_0    nividic
 
Comparing with @qfyu your installed packages, the version of some packages are different. Then I realized that you are using python 3.4. 

So I create another python 3.4 env as below:
conda create --no-default-packages -n test-lomap-python3 python=3.4
source activate test-lomap-python3
conda config --add channels nividic
conda install lomap

Here is the key package list in this python3.4 env 

boost                     1.56.0                   py34_1    nividic
graphviz                  2.38.0                        5  
lomap                     0.0.0                    py34_0    nividic
matplotlib                1.5.1               np110py34_0  
networkx                  1.11                     py34_0  
numpy                     1.10.4                   py34_2  
pygraphviz                1.4rc1                   py34_0    nividic
pyqt                      4.11.4                   py34_4  
python                    3.4.5                         0  
qt                        4.8.7                         4  
rdkit                     2015.09.2           np110py34_0    nividic

Using this python, I could also get the correct results. My conda version is 4.5.1. So @qfyu I suggest that you create a new empty conda environment and try again. If there is still a problem, could you post the error message here.

**Comment by shuail** [comment]
@davidlmobley I got the same error message as you did when I use my Mac to install lomap, it seems to be the graphviz compatible issue with Mac OS.

**Comment by davidlmobley** [comment]
Thanks, @shuail ! So it sounds like we have a separate issue to resolve relating to OS X then...?

**Comment by shuail** [comment]
@davidlmobley yes, I think graphviz may fail on certain OS X at least the latest OS X. Specifically it fails when graphviz try to convert the dot file (networkx output) to png file. Maybe we could either fix the compatible issue between graphviz and Mac, or find another package to convert the file format.

**Comment by qfyu** [comment]
@davidlmobley, I didn't get your error messages, and I am using ubuntu 14.
@shuail, I tried to create a new conda environment "test-lomap-python3" with your commands, the packages were same as yours, and the conda version was 4.2.9. However, the problems shown in (3) and (4) still existed.

**Comment by shuail** [comment]
@qfyu If the packages are all identical, I am not sure what could cause your problems at this point. For your problem 3, when you run the program, what is the printed out messages? Could you paste the message here.

**Comment by qfyu** [comment]
@shuail, I found the graphviz was a bit different: graphviz 2.38.0 1 mobleylab.

When I run the command "python example.py", no messages printed out on the screen, and I got some result files: out.txt, out_score_with_connection.txt, mcs.png, mcs_mapping_*_*.
#out.txt
#ID     FileName
0       1,3,7-trimethylnaphthalene.mol2
1       1-butyl-4-methylbenzene.mol2
2       2,6-dimethylnaphthalene.mol2
3       2-methyl-6-propylnaphthalene.mol2
4       2-methylnaphthalene.mol2
5       2-naftanol.mol2
6       methylcyclohexane.mol2
7       toluene.mol2

#out_score_with_connection.txt
Index_1   ,Index_2   ,Filename_1               ,Filename_2               ,Erc_sim        ,Str_sim        ,Loose_sim      ,Connect
0         ,1         ,1,3,7-trimethylnaphthalene.mol2,1-butyl-4-methylbenzene.mol2,1.00           ,0.11080        ,0.11080        ,No
0         ,2         ,1,3,7-trimethylnaphthalene.mol2,2,6-dimethylnaphthalene.mol2,1.00           ,0.90484        ,0.90484        ,Yes
...

#mcs_mapping_0_5
1 1
10 2
9 3
8 4
3 9
2 10
4 8
5 7
6 6
7 5
0 0

Thanks for the comments.

**Comment by shuail** [comment]
@qfyu I am not sure if the difference of graphviz would affect the result while I think it worth to try again with exact command (with the same order) of I did and see if you could get the identical packages.

**Comment by qfyu** [comment]
@shuail, the packages and results were obtained form the same order of your commands for the environment "test-lomap-python3".

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
