### ISSUE TITLE
Confusion about example output

### ISSUE THREAD

**Issue by ppxasjsm** [MobleyLab/Lomap#41]
If I run the example script I get an output as seen in the attached image. Two molecules and the detected MCSS. To me this looks wrong, but maybe I am just misunderstanding the output I am supposed to get. 
Should I not allow for rings to break and therefore one of the rings should be detected in the MCSS?
![mcs](https://user-images.githubusercontent.com/3668316/47167481-8a5df000-d2f6-11e8-82a1-74c342d4fd33.png)

**Comment by davidlmobley** [comment]
Right, usually breaking rings is not recommended for exactly such reasons.

Usually what I would do (when I was sstting up relative calculations) was to take a first pass where I did not break any rings at all (which is by far the easiest computationally) and then go back and consider ring-breaking transformations only if disallowing them resulted in disconnected subgraphs in the overall map.

**Comment by davidlmobley** [comment]
(In a normal MCSS search, with ring breaking allowed, it will just try to give you the largest substructure that is common even after breaking bonds; notice that in the middle molecule you posted there ARE five carbons in a row, so if you allow breaking of a bond in the aromatic ring you can get exactly the structure pictured on the right hand side. The right IS the largest common substructure, just not usually the one we would want to use for free energy calculations (because breaking that bond in the aromatic ring would be difficult, AND because our chemical intuition would be to preserve the aromatic ring).

That said you're also looking at a difficult transformation here, @ppxasjsm , because if you turn off breaking rings, there will be basically no connection between molecule 1 and molecule 2 (since one is bicyclic and the other has a single ring, and going from a bicyclic system to a single ring requires breaking one of the rings).
